Create bash scripts for running tests
- Move `runFullTestSuite` to `.sh/tests/runUnitChecks` as it was only
  performing unit tests / linting.
- Create separate scripts for running instrumentation tests, as well as
  the whole test suite for local development.
- Fix shellcheck issue with piping, instead using the logical OR when
  starting the sonar server.
- Run shellcheck validation as part of `runUnitChecks`.
- Use bash scripts instead of embedding the commands in the github
  composite actions for unit / instrumentation tests.
- Enable test sharding for the instrumentation tests.

diff --git a/.sh/sonar/verifyPath b/.sh/sonar/verifyPath
--- a/.sh/sonar/verifyPath
+++ b/.sh/sonar/verifyPath
@@ -5,11 +5,7 @@ set -o errexit
 
 # Start sonar server
 echo "- Ensuring that all commands are available on the PATH..."
-for TERMINAL_COMMAND in \
-  "sonar"
-do
-  if ! which "${TERMINAL_COMMAND}"; then
-    echo "  - Cannot find ${TERMINAL_COMMAND} on the PATH! Have you performed 'brew bundle --no-lock'?"
-    exit 11
-  fi
-done
+if ! which "sonar"; then
+  echo "  - Cannot find ${TERMINAL_COMMAND} on the PATH! Have you performed 'brew bundle --no-lock'?"
+  exit 11
+fi
